config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'


  resources :buoys do
    resources :photos, only: [:new, :create, :destroy]
    resources :bookings, only: [:new, :create, :destroy] do
      resources :reviews, only: [:new, :create]
    end
  end

  # resources :users, only: [:show] do
  #   resources :photos, only: [:new, :create, :destroy]
  # end

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'new', to: 'photos#new'
  # get 'create',


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validate :end_after_start
  belongs_to :buoy
  belongs_to :user
  has_one :review

  validates :start_date, presence: true
  validates :end_date, presence: true #, date: { after_or_equal_to:  :start_date}


  private

  def end_after_start
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/buoy.rb
class Buoy < ApplicationRecord
  searchkick
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :reviews, through: :bookings
  has_many :photos

  validates :title, presence: true
  validates :age, presence: true
  validates :category, presence: true, inclusion: { in: ["Food", "Animal", "Unicorn", "Cartoon", "Classic", "Weird"] }
  validates :capacity, presence: true
  validates :price_per_day, numericality: true, presence: true
  # validates :photo, presence:true
end

app/models/photo.rb
class Photo < ApplicationRecord
  # mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :buoy

  validates :photo, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  has_one :booking
  belongs_to :user

  validates :description, presence: true
  validates :rating, presence: true,  inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :buoys
  has_many :bookings
  has_many :reviews
  has_many :photos

  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @buoy = Buoy.find(params[:buoy_id])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @buoy = Buoy.find(params[:buoy_id])

    # calculating the renting days
    days = (bookings_params["end_date"].to_date - bookings_params["start_date"].to_date).to_i
    total_price = (days + 1) * @buoy.price_per_day

    @booking = Booking.new(bookings_params)
    @booking.total_price = total_price
    @booking.buoy = @buoy
    @booking.user = current_user
    if @booking.save
      @booking.save!
      redirect_to dashboard_path
    else
      @booking = Booking.new
      render "buoys/show"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.start_date >= Date.today
      @booking.destroy
      redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/buoys_controller.rb
class BuoysController < ApplicationController
  before_action :set_buoy, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @buoys = Buoy.search("#{params[:query]}")
      if @buoys.empty?
        @error_message = "No search result found"
        @buoys = Buoy.all
      end
    else
      @buoys = Buoy.all
    end
  end

  def show
    @booking = Booking.new
    @user_not_logged = !user_signed_in?
    date_range = []

    @bookings = Booking.where("buoy_id = ?", params[:id])

    @bookings.each do |booking|
      date_range << {from: booking.start_date, to: booking.end_date}
    end

    @date_json = date_range.to_json


    # If we want to implement an average rating
    # def mean(array)
    # array.inject(array.inject(0) { |sum, x| sum += x } / array.size.to_f
    # end
  end

  def new
    @array = ["Food", "Animal", "Unicorn", "Cartoon", "Classic", "Weird"]
    @buoy = Buoy.new
  end

  def create
    @buoy = Buoy.new(buoy_params)
    @buoy.user = current_user
    if @buoy.save
      redirect_to buoys_path
    else
      redirect_to new_buoy_path
    end
  end

  def edit
    @array = ["Food", "Animal", "Unicorn", "Cartoon", "Classic", "Weird"]
  end

  def update
    @buoy.update(buoy_params)
    redirect_to buoy_path(@buoy)
  end

  def destroy
    @buoy.delete
    redirect_to buoys_path
  end

  private

  def set_buoy
    @buoy = Buoy.find(params[:id])
  end

  def buoy_params
    params.require(:buoy).permit(:title, :age, :description, :capacity, :price_per_day, :category, :photo, :street, :photo_cache)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def dashboard
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking.review = @review
    @review.user = current_user
    if @review.save
      @review.save!
      redirect_to buoy_bookings_path(@booking)
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buoys/edit.html.erb
<div class="wrapper">

  <div class="container container-boxes">
        <div class="row">
          <div class="col-xs-12 col-md-6 left-form-container">
            <h2> Update: <%=@buoy.title %></h2>

            <div class="row">
              <div class="col-md-12">
                <%= simple_form_for @buoy do |f| %>
                <%= f.input :title, label: 'Title' %>
                <%= f.input :description, label: 'Description' %>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= f.input :category, as: :select, collection: @array %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :age, label: 'How old is your buoy?' %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :capacity, label: 'How many people fit on your buoy?' %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :price_per_day, label: 'What does your buoy cost for one day?' %>
              </div>

              <div class="col-md-12 col-xs-12">
                <%= f.input :street, label: 'Where does your buoy live?' %>
              </div>

              <div class="col-md-12 padding-bottom-left">
                <div class="photo-input">
                  <%= f.input :photo %>
                  <%= f.input :photo_cache, as: :hidden %>
                  <%= f.button :submit %>
                </div>
                      <%= link_to 'Back to buoys', buoys_path %>

              </div>
              <% end %>
            </div>
          </div>

          <div class="col-xs-12 col-md-6 image-padding-delete">
             <div class="right-form-container" style="background-image: url('<%= @buoy.photo_url%>');"></div>
          </div>
      </div>

  </div>
</div>

app/views/buoys/index.html.erb
<div class="wrapper">

    <div class="container-search">
      <div class="searchbox-box">
             <%= form_tag buoys_path, method: :get do %>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search for buoys"
              %>
            <% end %>
      </div>

</div>

  <div class="container-card">
    <% if @error_message == "No search result found" %>
      <p> <%= @error_message %></p>
    <% end %>
    <div class="row card-title-row">
      <h2> Check it out 👇</h2>
    </div>


    <div class="row card-row">
      <% @buoys.each do |buoy| %>
        <div class="col-xs-12 col-sm-4 col-md-3">
            <%= render 'components/card', buoy: buoy %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/buoys/new.html.erb
<div class="wrapper">

  <div class="container container-boxes">

        <div class="row">
          <div class="col-xs-12 col-md-6 left-form-container">
            <h2> Create a new buoy </h2>


            <div class="row">
              <div class="col-md-12">
                <%= simple_form_for @buoy do |f| %>
                <%= f.input :title, label: 'Title' %>
                <%= f.input :description, label: 'Description' %>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= f.input :category, as: :select, collection: @array %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :age, label: 'How old is your buoy?' %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :capacity, label: 'How many people fit on your buoy?' %>
              </div>

              <div class="col-md-6 col-xs-12">
                <%= f.input :price_per_day, label: 'What does your buoy cost for one day?' %>
              </div>

              <div class="col-md-12 col-xs-12">
                <%= f.input :street, label: 'Where does your buoy live?' %>
              </div>

              <div class="col-md-12 padding-bottom-left">
                <div class="photo-input">
                  <%= f.input :photo %>
                  <%= f.input :photo_cache, as: :hidden %>
                  <%= f.button :submit %>
                </div>
                      <%= link_to 'Back to buoys', buoys_path %>

              </div>
              <% end %>
            </div>
          </div>


          <div class="col-xs-12 col-md-6 image-padding-delete">
             <div class="right-form-container" style="background-image: url('<%= cl_image_path "vsixb78rasl46jol9nyv", crop: :fill %>');"></div>

          </div>
      </div>

  </div>
</div>

app/views/buoys/show.html.erb
<div class="wrapper-buoy-show">

  <div class="big-box">
    <div class="container container-buoy-show-hero">

      <button class="btn btn-outline-primary show-back-button">
        <%= link_to 'Back', url_for(:back) %>
      </button>

      <div class="row">
        <div class="col-xs-12">
          <div class="buoy-show-hero-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(' <%= cl_image_path(@buoy.photo); %>') ;">
          </div>
        </div>
      </div>
    </div>

    <div class="container container-buoy-show-info">
      <!-- <div class="row row-buoy-show-back">
        <button><%= link_to 'Back to list', url_for(:back) %></button>
      </div> -->
      <div class="row row-buoy-show-info">
        <div class="col-xs-12 col-md-8">
          <div class="buoy-show-infos">
            <p>#<%= @buoy.category %></p>
            <h2><%= @buoy.title %></h2>
            <div class="buoy-show-infos-avatar-name">
              <!-- add avatar picture here -->
             <p>Rented by <span><%= @buoy.user.first_name %> <%= @buoy.user.last_name %></span></p>
             <p> <i class="fas fa-map-marker"></i>  <%= @buoy.city %></p>
            </div>
            <div class="buoys-show-details">
              <span><i class="fas fa-clock"></i> <%= @buoy.age %> y/o</span>
              <span><i class="fas fa-user-friends"></i> <%= @buoy.capacity %> ppl</span>
            </div>
            <div class="buoys-show-details-description">
              <h4>Description</h4>
              <p><%= @buoy.description %></p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-md-4">
          <div class="buoy-show-booking">
            <div class="buoy-show-price">
              <h1><%= @buoy.price_per_day.to_i %> <i class="fas fa-euro-sign"></i> <br><span>per day</span></h1>
            </div>

            <!-- date picker -->
            <div class="buoy-show-datepicker" disable-dates= " <%= @date_json %> " >

              <div class="col-xs-12">
                <%= simple_form_for [@buoy, @booking] do |f| %>
                <div class="form-row">
                  <div class="datepicker-field">
                    <div>
                    <%= f.input :start_date, as: :string, wrapper_html: { :class => "inline_field_wrapper" }, label: 'Select dates'%>
                    <%= f.input :end_date, as: :hidden, wrapper_html: { :class => "inline_field_wrapper" } %>
                    </div>

                    <div class="datepicker-submit">
                    <%= f.button :submit, :disabled => @user_not_logged, class: 'btn btn-primary' %>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>

            </div>


            <div class="buoy-show-booking-links">
              <!-- here is the logic to make buttons invisible to non logged users or not owner of listing -->
              <% if current_user == @buoy.user %>
                <div class="buoy-show-owner-actions">
                  <p>You are the owner of this buoy</p>
                  <%= link_to 'Edit',edit_buoy_path(@buoy), class: 'btn btn-danger' %>
                  <%= link_to 'delete',buoy_path(@buoy), method: 'delete', class: 'btn btn-danger' %></div>
                </div>
              <% end %>
              <!-- end of buttons stuff -->
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container container-buoy-show-reviews">
      <div class="row-buoy-show-reviews">
        <div class="buoy-show-reviews">
          <h3>What people who rented this inflatable think...</h3>
          <!-- add iteration over reviews once they are implemented -->
            <p>...Well, actually, you will be the first to try it, go for it!
            </p>
           <!-- iterate over reviews -->
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'components/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'components/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="wrapper">

  <button class="btn btn-outline-primary show-back-button back-dashboard">
    <%= link_to 'Back', url_for(:back) %>
  </button>

  <div class="container">
    <div class="header">
      <h1>Dashboard</h1>
      <p>👋 Hello <%= current_user.first_name %> <%= current_user.last_name %>!</p>
    </div>


    <div class="dashboard-infos-tabs">


    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item active">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Manage bookings</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Manage listings</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Manage account information</a>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade active in" id="home" role="tabpanel" aria-labelledby="home-tab">
        <h3>Bookings</h3>
        <p>number of bookings: <%= current_user.bookings.size %></p>
        <div class="row card-row">
        <% current_user.bookings.each do |booking| %>
          <div class="col-xs-12 col-sm-4 col-md-3">
            <%= render 'components/bookingcard', booking: booking %>
          </div>
        <% end %>
      </div>
     </div>
     <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <h3>Buoys listings</h3>
      <p>number of buoys: <%= current_user.buoys.size %></p>
      <div class="row card-row">
        <% current_user.buoys.each do |buoy| %>
        <div class="col-xs-12 col-sm-4 col-md-3">
          <%= render 'components/card', buoy: buoy %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
      <h3>Account informations</h3>
      <p>first name: <%= current_user.first_name %></p>
      <p>last name: <%= current_user.last_name %></p>
      <p>email: <%= current_user.email %></p>
      <p>payment info: <%= current_user.payment %></p>
      <%= link_to 'Edit infos', edit_user_registration_path, class: 'btn btn-primary'%>
    </div>
    </div>





    </div>
  </div>

</div>

app/views/pages/home.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Oh Buoy!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/style.css">
  </head>

  <body>

    <div class="wrapper">

      <div class="banner background-image">
        <div class="banner-content">
          <h1>Oh Buoy!</h1>
          <p>Find your holidays savior</p>
          <%= link_to 'Rent an inflatable', buoys_path, class: 'btn btn-primary btn-lg' %>
        </div>
      </div>

      <div class="container-page">
        <div class="container container-valueprop">

          <div class="row row-title-valueprop">
            <div class="col-xs-12">
              <h1>Enjoy cheerful pool moments with friends and family</h1>
            </div>
          </div>

          <div class="row row-valueprop">
            <div class="col-xs-12 col-md-4">
              <div class="valueprop">
                <h1> Find the best inflatables</h1>
                <p>Find anty kind of inflatable to rent for your holidays. We gather the world biggest catalog of inflatables.</p>
              </div>
            </div>

            <div class="col-xs-12 col-md-4">
              <div class="valueprop">
                <h1> Do everything in one click</h1>
                <p>Our plateform has been built to offer the best experience so you can easily find what you want and book it in 10 seconds, no you got more time to plan your trip.</p>
              </div>
            </div>

            <div class="col-xs-12 col-md-4">
              <div class="valueprop">
                <h1> No hassle, we got you covered </h1>
                <p>We know life is full of unexpeted surprise. We got you covered by Allianz insurance. If the party blows, keep going !</p>
              </div>
            </div>

          </div>
        </div>

        <div class="container container-testimonials">
          <div class="row row-title-testimonials">
            <h1>What they think about our buoys</h1>
          </div>
          <div class="row row-testimonials">
            <div class="col-xs-12 col-md-6">
              <div class="testimonial">
                <h1>Scarlett</h1>
                <h2>has rented a wild colorful unicorn</h2>
                <p>Oh my buoy is so cool.. shoot ! I rented out my unicorn Josy last month while I was in a bootcamp. Josy went to Cascais with Pedro,n they had a lot of fun and I made crazy money.</p>
              </div>
            </div>
            <div class="col-xs-12 col-md-6">
              <div class="testimonial">
                <h1>Kaj</h1>
                <h2>has rented 2 watermelon inflatables</h2>
                <p>Really happy with this service, I rented two inflatables for my nieces, they had so much fun ! Thanks.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

    <!-- <p><%= link_to 'Login', new_user_session_path %></p>
    <p><%= link_to 'Sign Up', new_user_registration_path %></p> -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Write a review</h1>

    <%= simple_form_for @buoy do |f| %>
      <%= f.input :description, label: 'Description' %>
      <%= f.collection_radio_buttons :rating, [[5], [4], [3], [2], [1]], :first, :last, item_wrapper_tag: false, boolean_style: :inline do |b| %>
        <%= b.radio_button + b.label {'Rating'} %>
      <% end %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>